name: Test Running

permissions:
  contents: read
  actions: write # fount-charCI cache save/delete

on:
  workflow_dispatch:
  push:
    paths:
      - '**.mjs'
      - 'fount.json'
      - '.github/workflows/CI.yml'
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  test-running:
    runs-on: ubuntu-latest
    steps:
      - uses: steve02081504/fount-charCI@master
        with:
          CI-filepath: .github/workflows/CI.mjs
